name: Build PDFs
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            wmap:
              - 'WMAP/01_reanalysis/**'
            synch:
              - 'WMAP/04_synch/**'

      - name: Compile WMAP pdf
        if: steps.filter.outputs.wmap == 'true'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "WMAP/01_reanalysis/main.tex"
          work_in_root_file_dir: true
          continue_on_error: true

      - name: Compile synch pdf
        if: steps.filter.outputs.synch == 'true'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "WMAP/04_synch/main.tex"
          work_in_root_file_dir: true
          continue_on_error: true

      - name: Setup github-action bot 
        if: steps.filter.outputs.wmap == 'true' || steps.filter.outputs.frontend == 'synch'
        run: |
          mkdir -p PDFs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: move WMAP PDF
        if: steps.filter.outputs.wmap == 'true'
        run: |
          mv WMAP/01_reanalysis/main.pdf PDFs/WMAP_reanalysis.pdf

      - name: move synch PDF
        if: steps.filter.outputs.synch == 'true'
        run: |
          mv WMAP/04_synch/main.pdf PDFs/CG_synch.pdf

      - name: Push PDFs  
        if: steps.filter.outputs.wmap == 'true' || steps.filter.outputs.frontend == 'synch'
        run: |
          git add PDFs/*.pdf
          git commit -m "Uploading PDF"
          git push