name: Build Papers
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "WMAP/01_reanalysis/main.tex"
          work_in_root_file_dir: true

      - name: Push pdf
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Uploading compiled pdfs"
          git push